spring.application.name=wacdo
# Profil actif : "dev" déclenche l'insertion du jeu de test (DataFixture)
spring.profiles.active=dev

# Configuration de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/wacdo_db
spring.datasource.username=root
spring.datasource.password=root

# Configurations Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true