services:

  mysql:
    image: mysql:8.0
    container_name: wacdo-mysql
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wacdo_db
      MYSQL_USER: wacdo
      MYSQL_PASSWORD: wacdo
      TZ: Europe/Paris
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wacdo-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      TZ: Europe/Paris
    depends_on:
      - mysql
    restart: unless-stopped

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev-oauth2
    restart: always
    ports:
      - "8082:80"      # Web UI
      - "2525:25"      # SMTP server
      - "8083:143"     # IMAP server

volumes:
  mysql_data: